<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7xXxmY8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7xXxmY8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7xXxmY8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7xXxmY8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7xXxmY8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7xXxmY8',
    'container.build_id' => 'ed111e8f',
    'container.build_time' => 1592253336,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7xXxmY8');
