<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCZrk9d0\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCZrk9d0/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCZrk9d0.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCZrk9d0\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCZrk9d0\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CZrk9d0',
    'container.build_id' => 'a9af7b57',
    'container.build_time' => 1592845968,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCZrk9d0');
